### ISSUE TITLE
Mod causes server to crash

### ISSUE THREAD

**Issue by BestMordaEver** [andersblomqvist/minecraft-well-fed-mod#1]
Isolated the crash issue to this mod. Logfile points out that during registration, mod requests the GuiScreen element.
Stacktrace here: https://pastebin.com/5nTbE8cM
Minecraft 1.13.2, Forge 25.0.219

**Comment by andersblomqvist** [comment]
Issue is now solved. Please check mod page for new .jar file. Thanks 👍
