### ISSUE TITLE
1.16.2-1.3.1 crashes dedicated server Forge 1.16.1 build 32.0.108

### ISSUE THREAD

**Issue by kreezxil** [andersblomqvist/minecraft-well-fed-mod#4]
Notes:
     you tagged it for 1.16.1 but it insists on 1.16.2

crash report: 
http://paste.ubuntu.com/p/2NYRRwv4Zc/

fml server latest: 
http://paste.ubuntu.com/p/w7kcJ5sMN8/

**Comment by andersblomqvist** [comment]
Sorry about that. It's of course meant that the mod for 1.16.2 should run on a 1.16.2 server. Updated the file now so it shows correct version
